### ISSUE TITLE
TeX reports error ``undefined control sequence'' when compiling.

### ISSUE THREAD

**Issue by Liam0205** [pecorarista/sakuratheme#1]
Hi @pecorarista ,

I'm very glad to see your great contribution to beamer themes. For this `sakuratheme`, I met a problem when I was trying to compile it.

The environment information is listed below:

* Win7, Pro., SP1
* TeX Live 2016, with all packages updated
* UTF-8 encoding, as required by LuaLaTeX
* LuaLaTeX

When compiling, LuaTeX complained for an undefined control sequence:

```tex
! Undefined control sequence.
\@inittone ->\@getaccshift 
                           \let \c@lcshift \@toneshift \let \pr@vtone \relax...

l.134 \end{frame}
               
? 
```

Could you help me to solve this problem? Any hints or clues would be appreciated.

**Comment by pecorarista** [comment]
Thank you for reporting.
I'm sorry for the late reply.

I don't have Windows now and I cannot reproduce the problem.
Do you have the same problem in Metropolis theme?

**Comment by pecorarista** [comment]
I remove many codes related to pgf. Maybe it is now solved.
